export let datos = [
    {
        year : "2023",
        title : "Compilador para el lenguaje T-Swift",
        descripcion : "Recibe una entrada de código fuente T-Swift generada por parte del usuario para generar una salida que será una representación intermedia en formato de código de tres direcciones, este formato utiliza sentencias del lenguaje C para su posterior ejecución.",
        repositorio : "https://github.com/rubenralda/OLC2_proyecto2.git",
        tags : ["Go", "ANTLR4", "Fiber", "JS", "HTML", "CSS"],
        curso : "Organización de lenguajes y compiladores 2",
    },
    {
        year : "2023",
        title : "Aplicación de comandos",
        descripcion : "Cuenta con un cliente para ingresar los comandos, se alojó en un bucket S3 y consumía una API alojada en una EC2 que interpretaba los comandos de los cuales se simulaban en archivos binarios que representan los discos.",
        repositorio : "https://github.com/rubenralda/MIA_Proyecto_2.git",
        tags : ["Python", "PLY", "Flask", "JS", "HTML", "CSS", "AWS"],
        curso : "Manejo e implementación de archivos",
    },
    {
        year : "2023",
        title : "Intéprete para el lenguaje T-Swift",
        descripcion : "T-Swift es un lenguaje basado en el popular lenguaje de programación Swift, la aplicación consiste en este intérprete diseñado con el patrón visitor y el patrón intérprete, ejecuta las intrucciones y muestra la salida del algoritmo.",
        repositorio : "https://github.com/rubenralda/OLC2_Proyecto1_202111835.git",
        tags : ["Go", "ANTLR4", "Fiber", "JS", "HTML", "CSS"],
        curso : "Organización de lenguajes y compiladores 2",
    },
    {
        year : "2023",
        title : "Juego japonés Sokoban en ensamblador",
        descripcion : "El jugador tiene como principal objetivo empujar una serie de cajas hasta conseguir que estas se ubiquen en ciertas posiciones. Cuando el jugador consigue lo anterior se le permite avanzar de nivel y acumular más puntos. Empleando las características gráficas que brinda DOS y el conjunto de interrupciones que este provee.",
        repositorio : "https://github.com/rubenralda/ACE1-23VJ0778202111835PROY2.git",
        tags : ["MASM 6.11"],
        curso : "Arquitectura de computadores y ensambladores 1",
    },
    {
        year : "2023",
        title : "Sistema para punto de venta en ensamblador",
        descripcion : "Tiene la capacidad de gestionar el inventario de productos, control de ventas y clientes. Además, tiene un módulo de reportería que trabaja sobre los datos almacenados por el sistema y un módulo para carga masiva de datos.",
        repositorio : "https://github.com/rubenralda/ACE1-23VJ0778202111835PRA2.git",
        tags : ["MASM 6.11"],
        curso : "Arquitectura de computadores y ensambladores 1",
    },
    {
        year : "2023",
        title : "TypeWise",
        descripcion : "Intérprete para un nuevo lenguaje TypeWise utilizando el patrón intérprete para el lado del BackEnd y un editor sencillo en el FrontEnd.",
        repositorio : "https://github.com/rubenralda/OLC_Proyecto2_202111835.git",
        tags : ["JavaScript", "Jison", "Node.js", "Express", "HTML", "CSS"],
        curso : "Organización de Lenguajes y compiladores 1",
    },
    {
        year : "2023",
        title : "GoDrive",
        descripcion : "Fase 1: Implementación de estructuras de datos lineales para guardar la información de estudiantes. Fase 2: Implementación de un árbol AVL, árbol N-ario para crear, eliminar y subir archivos además de una matriz Dispersa para guardar los permisos de archivos por usuario. Fase 3: Cambio de almacenamiento de usuarios a una tabla Hash y un nuevo sistema de mensajería simulando un blockchain.",
        repositorio : "https://github.com/rubenralda/EDD_1S2023_PY_202111835.git",
        tags : ["Go", "JavaScript", "HTML", "CSS"],
        curso : "Estructuras de Datos",
    },
    {
        year : "2023",
        title : "EXREGAN",
        descripcion : "Intérprete de Expresiones Regulares en notación polaca capaz de realizar el Método del Árbol y el Método de Thompson mostrando los reportes del procedimiento y pudiendo verificar entradas del scanner generado.",
        repositorio : "https://github.com/rubenralda/OLC_Proyecto1_202111835.git",
        tags : ["Jflex", "Cup", "JAVA"],
        curso : "Organización de Lenguajes y compiladores 1",
    },
    {
        year : "2022",
        title : "Intérprete creado con autómata de pila y fínito determinístico",
        descripcion : "Diseño y creación de páginas web estáticas de una forma sencilla. Se generá su traducción a HTML y CSS, en caso no exista ningún error en la compilación del código.",
        repositorio : "https://github.com/rubenralda/LFP_Proyecto2_202111835.git",
        tags : ["Tkinter", "Python"],
        curso : "Lenguajes formales y de programación",
    },
    {
        year : "2022",
        title : "Analizador léxico apartir de un AFD",
        descripcion : "Lectura de código fuente capaz de identificar un lenguaje dado, identificando los errores léxicos y ejecutando las instrucciones correspondientes.",
        repositorio : "https://github.com/rubenralda/LFP_Proyecto1_202111835.git",
        tags : ["Tkinter", "Python"],
        curso : "Lenguajes formales y de programación",
    },
    {
        year : "2022",
        title : "MyMusicYourMusic",
        descripcion : "Implementación de una API que brinda servicios utilizando el Protocolo HTTP bajo el concepto de programación orientada a objetos (POO).",
        repositorio : "https://github.com/rubenralda/IPC2_Proyecto2_202111835.git",
        tags : ["Django", "Python", "Flask", "ElementTree"],
        curso : "Introducción a la programación y computación 2",
    },
    {
        year : "2022",
        title : "Poke Busqueda",
        descripcion : "Se utiliza archivos json como base de datos para iniciar sesión y hacer una busqueda de pokemon por el tipo, número o nombre.",
        repositorio : "https://github.com/rubenralda/IPC1-Proyecto2_202111835.git",
        tags : ["HTML", "CSS", "JavaScript", "Node.js", "Express"],
        curso : "Introducción a la programación y computación 1",
    },
    {
        year : "2019",
        title : "Mi biblioteca",
        descripcion : "CRUD de una biblioteca conectada a una base de datos en Mysql con PHP",
        repositorio : "https://github.com/rubenralda/Ejercicios_PHP.git",
        tags : ["PHP", "phpmyAdmin", "HTML", "Bootstrap", "MySql", "XAMPP"],
        curso : "Programación colegio ITC",
    },
]